site_name: Awesome Go Educations
site_url: https://github.com/mehdihadeli/awesome-go-education
site_description: A curated list of awesome articles and resources for learning and practicing about Go and its related technologies.
docs_dir: 
repo_name: mehdihadeli/awesome-go-education
repo_url: https://github.com/mehdihadeli/awesome-go-education
edit_uri: edit/main/docs/
theme: 
  name: material 
  palette:
    primary: 'deep purple'
    accent: 'indigo'  
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:pymdownx.emoji.twemoji
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
  - Web / REST:
    - WEB / REST : web/web-rest.md
    - Gin : web/gin.md
    - Beego : web/beego.md
    - Echo : web/echo.md
    - Fiber : web/fiber.md
    - Iris : web/iris.md
  - Go Instructions:
    - Go: go-instructions/go.md
    - Control Flow: go-instructions/control-flow.md
    - Conversion: go-instructions/conversion.md
    - Defer: go-instructions/defer.md
    - Dep: go-instructions/dep.md
    - File: go-instructions/file.md
    - Function: go-instructions/function.md
    - GOPATH: go-instructions/gopath.md
    - Init: go-instructions/init.md
    - Interface: go-instructions/interface.md
    - Loops: go-instructions/loops.md
    - Method: go-instructions/method.md
    - Modules & Packages: go-instructions/modules-packages.md
    - Pointer: go-instructions/pointer.md
    - Struct: go-instructions/struct.md
    - Switch: go-instructions/switch.md
    - Variables: go-instructions/variables.md
    - Data Types: 
      - Data Types: go-instructions/data-types/data-types.md
      - Strings: go-instructions/data-types/strings.md
    - Collections:
      - Array: go-instructions/collections/arrays.md
      - Maps: go-instructions/collections/maps.md
      - Slices: go-instructions/collections/slices.md
  - ORM: 
    - ORM: orm/orm.md
    - gorm: orm/gorm.md
  - Logging:
    - Logging: logging/logging.md
    - Zap: logging/zap.md
  - DDD: ddd.md
  - Clean Architecture: clean-architecture.md
  - CQRS: cqrs.md
  - Concurrency: concurrency.md
  - Best Practices: best-practices.md
  - Error Handling: error-handling.md
  - Microservices : microservices.md
  - OOP : oop.md
  - Project Structure : project-structure.md
  - Software Architecture : software-architecture.md

copyright: 2021 <a href="https://github.com/mehdihadeli">Mehdi Hadeli</a>.
#remote_branch: gh-pages 
#remote_name: origin
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mehdi_hadeli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mehdihadeli
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mehdihadeli
